"""
Django settings for hive_sbi_api project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-st0ej2-ii&ffp6z*1y1orrExzhkqo7*(+k++(bdrzwg4oqj4_tl9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

INSTALLED_APPS = [
    'corsheaders',
    'django_celery_results',
    'rest_framework',
    'django_filters',
    'drf_yasg',
] + INSTALLED_APPS

INSTALLED_APPS = [
    'hive_sbi_api.core',
    'hive_sbi_api.v0',
    'hive_sbi_api.v1',
    'hive_sbi_api.sbi',
    'hive_sbi_api.hivesql',
    'hive_sbi_api.steem',
]  + INSTALLED_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hive_sbi_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hive_sbi_api.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME':     os.environ.get('POSTGRES_DB',       ''),
        'USER':     os.environ.get('POSTGRES_USER',     ''),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
        'HOST':     os.environ.get('POSTGRES_HOST',     ''),
        'PORT':     os.environ.get('POSTGRES_PORT',     ''),
    },
    'sbi': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('SBI_DB_NAME', ''),
        'USER': os.environ.get('SBI_DB_USER', ''),
        'PASSWORD': os.environ.get('SBI_DB_PASSWORD', ''),
        'HOST': os.environ.get('SBI_DB_HOST', ''),
        'PORT': os.environ.get('SBI_DB_PORT', ''),
    },
    'sbi_steem_ops': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('SBI_STEEM_OPS_DB', ''),
        'USER': os.environ.get('SBI_DB_USER', ''),
        'PASSWORD': os.environ.get('SBI_DB_PASSWORD', ''),
        'HOST': os.environ.get('SBI_DB_HOST', ''),
        'PORT': os.environ.get('SBI_DB_PORT', ''),
    },
    "hivesql": {
        "ENGINE": "mssql",
        "NAME": os.environ.get('HIVESQL_DB_NAME', ''),
        "USER": os.environ.get('HIVESQL_USER', ''),
        "PASSWORD": os.environ.get('HIVESQL_PASSWORD', ''),
        "HOST": os.environ.get('HIVESQL_HOST', ''),
        "PORT": os.environ.get('HIVESQL_PORT', "1433"),
        # "OPTIONS": {"driver": "ODBC Driver 17 for SQL Server",},
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_METADATA_CLASS': None,
    'PAGE_SIZE': 200,
}

SWAGGER_SETTINGS = {
   'USE_SESSION_AUTH': False,
   'SECURITY_DEFINITIONS': None,
}

CELERY_BROKER_URL = 'redis://redis:6379'
CELERY_RESULT_BACKEND = 'django-db'
